### ISSUE TITLE
[REQUEST] Support compatibility for Ruby versions

### ISSUE THREAD

**Issue by etagwerker** [fastruby/next_rails#115]
## Description

Just like this gem supports this:

```
# Show gems that don't work with Rails 5.2.0
bundle_report compatibility --rails-version=5.2.0
```

It would be nice to support:

```
# Show gems that don't work with Rails 5.2.0
bundle_report compatibility --ruby-version=3.1.0
```

## Possible Implementation

The code would use every gemspec's required_ruby_version attribute:  https://github.com/fastruby/skunk/blob/main/skunk.gemspec#L17C8-L17C29

## Resources:

Unfortunately, the required_ruby_version is not a required attribute in a gemspec, so the implementation would need to take that into account. More here: https://guides.rubygems.org/specification-reference/#required_ruby_version

**I will abide by the [code of conduct](https://github.com/fastruby/next_rails/blob/main/CODE_OF_CONDUCT.md)**

**Comment by JuanVqz** [comment]
This seems duplicated #17
