### ISSUE TITLE
NameError:   uninitialized constant DeprecationTracker

### ISSUE THREAD

**Issue by prateekvyas2121** [fastruby/next_rails#12]
i am not able to use this gem!
i'd be thankful if i get some support!

```
prateek@prateek-Vostro-3558:~/Desktop/myProject/project_name$ DEPRECATION_TRACKER=save rspec

An error occurred while loading spec_helper.
Failure/Error:
  DeprecationTracker.track_rspec(
    config,
    shitlist_path: "spec/support/deprecation_warning.shitlist.json",
    mode: ENV["DEPRECATION_TRACKER"],
    transform_message: -> (message) { message.gsub("#{Rails.root}/", "") }
  )

NameError:
  uninitialized constant DeprecationTracker
```

**Comment by etagwerker** [comment]
@prateekvyas2121 Thanks for reporting this! Could you confirm what version of `next_rails` you are using? Are you using v1.0.2? 

One thing that you might want to try is this: 

1. Add `next_rails` to your Gemfile
2. Run `bundle install`
3. Run your test suite with `bundle exec`

```
DEPRECATION_TRACKER=save bundle exec rspec
```

I just tested the same command in one of my OSS projects (https://github.com/fastruby/points) and it seems to work fine.

**Comment by prateekvyas2121** [comment]
i did the exact same although..but there's not a significant difference!

**Comment by etagwerker** [comment]
@prateekvyas2121 Could you please share your `Gemfile` over here? I just tested this in one of my OSS Rails projects (https://github.com/fastruby/points) and it works fine: https://gist.github.com/etagwerker/4c56ab6cb66c1c88712c955d5467e549

You can see what my Gemfile looks like over here: https://github.com/fastruby/points/blob/main/Gemfile#L96-L98 

Also, could you please share a backtrace over here? (not just the error message: `uninitialized constant DeprecationTracker`)

**Comment by buys-fran** [comment]
I am seeing the same error. I have attached the gemfile.

If it helps I am running on OSS with ruby '2.6.5'.

Backtrace: https://gist.github.com/buys-fran/7e15ca06ec001b5d1446750097eccb20
Gemfile: https://gist.github.com/buys-fran/89692fe823a7edc19b64e8ab3009cb9f

**Comment by buys-fran** [comment]
I think we can close this issue. I found the problem.

According to the readme here: https://github.com/fastruby/next_rails#deprecation-tracking
`If you're using RSpec, add this snippet to rails_helper.rb or spec_helper.rb (whichever loads Rails).`

Once I moved the snippit to my rails_helper it worked perfectly.

**Comment by etagwerker** [comment]
@buys-fran Got it, thanks!
