### ISSUE TITLE
[BUG] Upgrading to 1.4.0 increases our request time from ~200ms to 3-6s on every page load in development

### ISSUE THREAD

**Issue by davidwessman** [fastruby/next_rails#130]
## Expected Behavior
- next_rails should to affect the response time of our app at all

## Actual Behavior
- Rails 7.1.3.4
- next_rails 1.4.0

## Possible Fix

- Not including the gem in development group (saw a comment in the README to put it in test)

## To Reproduce

Install `next_rails` in Gemfile like:

```ruby
gem "next_rails", "~> 1.4.0"
```

Reload a page multiple time and check the response time in devtools.

Remove it and see if it is faster.

Would love to create a new app to test it in, but I have no time :( 

If the solution is to recommend `bundle add next_rails --group development` then I am okay with that 🙂 

## Additional Information

**I will abide by the [code of conduct](https://github.com/fastruby/next_rails/blob/main/CODE_OF_CONDUCT.md)**

**Comment by etagwerker** [comment]
@davidwessman Thanks for sharing this weird behavior! 

This is very strange. `next_rails` doesn't really do anything until you call it. Are you using `NextRails.next?` a lot in your controllers? 

Also, the way you described the issue makes me think that everything was fine with `next_rails` version < 1.4.0? Is that the case? 

Please let us know!

**Comment by davidwessman** [comment]
> This is very strange. `next_rails` doesn't really do anything until you call it. Are you using `NextRails.next?` a lot in your controllers? 

No, we used only the deprecation tracker during test runs.

Did the behavior of that one change in 1.4.0? Maybe we have too many deprecation warnings for it to handle? We did not do anything explicit in development though.

> Also, the way you described the issue makes me think that everything was fine with `next_rails` version < 1.4.0? Is that the case? 

Yes, I had to do a git bisect to find that it was the dependabot update to 1.4.0 that made it slow.

Nothing weird changed in the lock file, the only thing was switching from colorize to rainbow 🌈

**Comment by jan-bw** [comment]
Hi. We just run into the same issue. Some of our endpoints slowed down after upgrading from 1.3.0 to 1.4.0.

I tried to narrow down the issue and I was able to reproduce the slower response times locally. The example endpoint responses went from ca 800ms to 960ms.

It looks like the culprit it the rainbow refinement (https://github.com/ku1ik/rainbow/blob/master/lib/rainbow/refinement.rb). I changed the code locally:
- removed the `require "rainbow/refinement"` and `using Rainbow`
- replaced the `.bold` and other helper methods with direct `Rainbow` syntax i.e. `Rainbow("string").bold`

That fixed the issue for me. I could open a PR with those changes if you are fine with that approach :)

**Comment by davidwessman** [comment]
Nice find! 👏🏻

**Comment by etagwerker** [comment]
@davidwessman Thanks for reporting this! 🙏

@jan-bw thanks for the detailed follow up! It would be much appreciated if you opened a PR for this. ❤️

**Comment by jan-bw** [comment]
I opened a PR :)

Additionally, after spending a bit more time looking into it I realised it's not just a monkey patch issue but rather an issue with the `refine` and `method_missing` usage. I was even able to slow down my app by adding an initializer:
```
module Lol
  refine String do
    def method_missing(method_name, *args, &block)
      super
    end
  end
end
```
this cause my app to slow down quite a bit too 😱 

Nevertheless the PR seems to be solving it for this gem!

**Comment by etagwerker** [comment]
I just pushed v1.4.1 with a patch for this. Thank you, @davidwessman and @jan-bw! 🙏🏼
