### ISSUE TITLE
next_rails requires actionview, which depends on activesupport

### ISSUE THREAD

**Issue by geetfun** [fastruby/next_rails#18]
Problem:

`next_rails` requires `actionview`, of which the minimum attainable version is 4.1.0: https://rubygems.org/gems/actionview/versions

In this version, it depends on `activesupport` version 4.1.2rc:

```
Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (= 3.2.22.5)

  In Gemfile:
    actionview (~> 4.1) was resolved to 4.1.2.rc1, which depends on
      activesupport (= 4.1.2.rc1)

    rails (= 3.2.22.5) was resolved to 3.2.22.5, which depends on
      activesupport (= 3.2.22.5)
```

As a result, `next_rails` cannot be used for Rails 3 upgrade projects.

**Comment by etagwerker** [comment]
@geetfun Weird. I thought we resolved that issue over here: https://github.com/fastruby/next_rails/pull/6 

What version of `next_rails` are you using?

**Comment by geetfun** [comment]
@etagwerker It was version 1.0.2 from rubygems.

In the recent client project (Rails 3.2), I ended up forking the fastruby/next_rails repo here (https://github.com/geetfun/next_rails) and removed the `actionview` dependency altogether, and it seemed to work. It looks like the dependency is used for formatting the output (eg. for `time_ago_in_words`). When it isn't available, the code uses `strftime`.

Here is the relevant lines in the codebase: https://github.com/fastruby/next_rails/blob/38dd580ecfb34c5bd4dfdc63c78c95e1322eb360/lib/next_rails/gem_info.rb#L54-L60

I think the reason it didn't work is because `actionview` is only available > 4.1, and isn't defined/available in Rails 3.2 as it was still part of ActionPack: https://github.com/rails/rails/blob/v3.2.22.5/actionpack/lib/action_view.rb.

**Comment by etagwerker** [comment]
@geetfun I think I know what the problem is, it seems that we haven't pushed v1.0.3 which declares `actionview` as a development dependency.

v1.0.2 declared `actionview` as a runtime dependency. I believe that is why you couldn't install it: https://guides.rubygems.org/patterns/#declaring-dependencies

Could you please try running `next_rails` from GitHub's main branch and report back? I believe this is fixed in `main` but not yet released in Rubygems...

**Comment by geetfun** [comment]
> Could you please try running next_rails from GitHub's main branch and report back? I believe this is fixed in main but not yet released in Rubygems...

Works!
