### ISSUE TITLE
Not working with github repositories

### ISSUE THREAD

**Issue by obromios** [fastruby/next_rails#31]
In my Gemfile I have a number of gems that use the github source because the gem has not been updated e.g.
`gem 'apparition', github: 'twalpole/apparition', ref: 'ca86be4d54af835d531dbcd2b86e7b2c77f85f34'`
When I run `next bundle update` I get the following error
`The git source https://github.com/twalpole/apparition.git is not yet checked out. Please run `bundle install` before trying to start your application`
Running `bundle install` just does a successful installation but does not fix the problem. 

 Is there a way to work around this?

**Comment by arielj** [comment]
seems like `next bundle install` is needed to fix this problem, sadly that error message comes from bundler, not next rails, so I don't think we can customize it to say `Please run next bundle install`.
