### ISSUE TITLE
Ruby 2.6.5: Running next --init fails with zsh: command not found: next

### ISSUE THREAD

**Issue by belgoros** [fastruby/next_rails#36]
I followed the [installation](https://github.com/fastruby/next_rails#installation) steps, then run the command described in [Setup](https://github.com/fastruby/next_rails#setup) section:
```
next --init
```
It failed with `zsh: command not found: next` (I'm using Oh My Zsh terminal). 
Reproduced on:
- macOS Monterey
- Rails 5.2.6.2
- Ruby 2.6.5.

What am I missing?

**Comment by rishijain** [comment]
I tried to reproduce this on my ubuntu machine with zsh but I was not able to reproduce it. 
Are you still facing this issue @belgoros ?

**Comment by belgoros** [comment]
I've just tried it again and everything worked as expected (no idea why it was the case before). I'll close the issue. Thank you for your feedback.
