### ISSUE TITLE
README doesn't include a Development section or Contributing section. 

### ISSUE THREAD

**Issue by FionaDL** [fastruby/next_rails#47]
The README has information about adding the gem to your project, but no information about contributing or setting up the repo locally. 

We should add sections dealing with this information. 

The information should include how to setup the project locally and what contribution guidelines we have. For example:
I wasn't sure what link to add in the CHANGELOG. This could be described in the README

**Comment by etagwerker** [comment]
@FionaDL Great point and thanks for reporting this! I think we should follow the example in `skunk`, there is a CONTRIBUTING.md that has all this information: https://github.com/fastruby/skunk/blame/main/CONTRIBUTING.md

Then README.md could point people in the direction of CONTRIBUTING.md
