### ISSUE TITLE
Question: Why do I need next_rails?

### ISSUE THREAD

**Issue by jeffsaremi** [fastruby/next_rails#58]
If I can simply do this:

```BUNDLE_GEMFILE=Gemfile.next bundle install``` or ```BUNDLE_GEMFILE=Gemfile.next bundle exec ...```

**Comment by StephaneP** [comment]
yes you can do that but it offers a few other things, might want to review the code or check out the talk on youtube it explains it all.

**Comment by rishijain** [comment]
It helps in dual booting your rails app. So you can run different versions of rails and other gems.
You can read more about it here: https://www.fastruby.io/blog/upgrade-rails/dual-boot/dual-boot-with-rails-6-0-beta.html

**Comment by rishijain** [comment]
Closing this for now. Let us know if you have any more questions regarding the gem and its usage.
