### ISSUE TITLE
[BUG] bundle_report outdated/compatibility --json returns invalid option: --json

### ISSUE THREAD

**Issue by JuanVqz** [fastruby/next_rails#86]
The [readme#usage](https://github.com/fastruby/next_rails#usage) section suggests using a format flag but it didn't work.

## Expected Behavior

Return the outdated report in JSON format
```bash
bundle_report outdated --json
```

## Actual Behavior

```bash
bundle_report outdated --json
```

returns `invalid option: --json`

**I will abide by the [code of conduct](https://github.com/fastruby/next_rails/blob/main/CODE_OF_CONDUCT.md)**

**Comment by rishijain** [comment]
Hey @JuanVqz I was able to reproduce this error on next_rails version 1.0.5.
But then upgrading it to latest next_rails 1.2.2 fixed this issue for me. Can you try and upgrade and check if that works for you?

**Comment by JuanVqz** [comment]
you are right, it is working after upgrading to `1.2.2`, I had `1.2.1` through
