### ISSUE TITLE
[REQUEST] A command to `promote` the next rails version

### ISSUE THREAD

**Issue by arielj** [fastruby/next_rails#88]
## Description

When we are ready to move to the `next` version after some time of dual booting, we have to do some manual steps:
- remove the old `Gemfile.lock`, replace it with the `Gemfile.next.lock`
- change the `if / else` conditional in the Gemfile to set the `next` as the current and add a new next (or remove the conditionals)
- go through the code looking for conditionals to remove them
- we might want to set up the next dual boot jump or maybe not and wait until deprecations are fixed for example

It would be nice to have something like `next promote` or something like that to automate these steps or at least facilitate them. Maybe with some arguments to decide if we want to re-add the new dual booting or just remove it, if we want to do something with conditionals in the code, etc (though we would need to define some conventions for this to make sense)

## Possible Implementation

I don't have an implementation idea, I imagine some simple file renaming, file parsing with search/replace can work for the basics.

## Resources:

I don't have any resource to link to either.

**I will abide by the [code of conduct](https://github.com/fastruby/next_rails/blob/main/CODE_OF_CONDUCT.md)**

**Comment by fbuys** [comment]
This seems like a fairly complex change, especially:

- go through the code looking for conditionals to remove them

Do any part of this feature can be implemented and still add value? I am wondering if it would make sense to implement most of what is described but leave the conditionals in the code until we have time to discuss it a bit more.

**Comment by etagwerker** [comment]
On second thought, I think this falls outside the scope of this gem and it is not that easy to implement, so I think we won't be implementing this feature. Thanks for taking the time to suggest it! 💯
