### ISSUE TITLE
bundle_report indicates no compatibility with given Rails version despite there is a compatible one

### ISSUE THREAD

**Issue by matiasgarcia** [fastruby/next_rails#9]
Hello.

I am using the `next_rails` gem to walk me through the easiest paths to upgrade our codebase.

I had the following dependencies:

```
gem 'rails',                          '4.2.11.3'
gem 'coffee-rails',                 '4.0.1'
```

When running `bundle exec bundle_report compatibility --rails-version=5.0.0` I got:

```
=> Incompatible with Rails 5.0.0 (with no new compatible versions):
These gems will need to be removed or replaced before upgrading to Rails 5.0.0.
coffee-rails 4.0.1 - new version, 5.0.0, is not compatible with Rails 5.0.0
15 gems incompatible with Rails 5.0.0
```

However, [version 4.1.1](https://github.com/rails/coffee-rails/blob/master/CHANGELOG.md#411-december-18-2015) is compatible with Rails 5.

I am wondering if improving this report to try find the bare minimum version that's compatible with Rails 5 is possible or is out of scope of this gem.

Regards, Matias.

**Comment by tiagocasanovapt** [comment]
Same issue, an example with `activeresource`, this can be misleading when checking wether to update or drop a gem in a project

```
=> Incompatible with Rails 4.0.0 (with no new compatible versions):
These gems will need to be removed or replaced before upgrading to Rails 4.0.0.

activeresource 3.2.22.5 - new version, 5.1.1, is not compatible with Rails 4.0.0
```
